image: Ubuntu  # образ для сборки

stack: jdk 11  # версия JDK

branches:
  only:
    - master  # ветка git

build: off  # будем использовать свой скрипт сборки

install:
  - java -jar ./artifacts/app-card-delivery-2.jar -port=7777 &
  # запускаем SUT (& означает, что в фоновом режиме не блокируем терминал для запуска тестов)
  - chmod +x gradlew


build_script:
  - ./gradlew test --info -Dselenide.headless=true